import golden from '@/public/levels/golden.png';
import vipimg from '@/public/levels/5.png';
import sliverimg from '@/public/levels/silver.png';
import bronzeimg from '@/public/levels/bronze.png';
import avatarImg from '@/public/profile-photo.jpg';

export const forecasters = [
  {
    id: 1,
    level: 'vip',
    data: [
      {
        id: 1,
        levelurl: vipimg,
        rank: '1st',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 2,
        levelurl: vipimg,
        rank: '2nd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 3,
        levelurl: vipimg,
        rank: '3rd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 4,
        levelurl: vipimg,
        rank: '4th',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
    ],
  },
  {
    id: 2,
    level: 'golden',
    data: [
      {
        id: 1,
        levelurl: golden,
        rank: '1st',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 2,
        levelurl: golden,
        rank: '2nd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 3,
        levelurl: golden,
        rank: '3rd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 4,
        levelurl: golden,
        rank: '4th',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
    ],
  },
  {
    id: 3,
    level: 'sliver',
    data: [
      {
        id: 1,
        levelurl: sliverimg,
        rank: '1st',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 2,
        levelurl: sliverimg,
        rank: '2nd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 3,
        levelurl: sliverimg,
        rank: '3rd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 4,
        levelurl: sliverimg,
        rank: '4th',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
    ],
  },
  {
    id: 4,
    level: 'bronze',
    data: [
      {
        id: 1,
        levelurl: bronzeimg,
        rank: '1st',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 2,
        levelurl: bronzeimg,
        rank: '2nd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 3,
        levelurl: bronzeimg,
        rank: '3rd',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
      {
        id: 4,
        levelurl: bronzeimg,
        rank: '4th',
        imgurl: avatarImg,
        username: `@Johnny`,
        winRate: '39%',
        avrOdds: '76%',
        copied: '89%',
      },
    ],
  },
];
