import React from 'react';

export const metadata = {
  title: 'Leader Board',
  description: 'Generated by create next app',
  keywords: 'Betting, Odds, Football',
};

const DashboadPage = () => {
  return <div>DashBoard</div>;
};

export default DashboadPage;
